const days=[
 {d:'25',w:'FRI',city:'kyoto',label:'KYOTO',title:'Land, transfer & Higashiyama',text:'HND 04:55 → Shinagawa → reserved Nozomi. Leave bags, then Kiyomizu-dera, old streets and Gion.',tag:'Arrival'},
 {d:'26',w:'SAT',city:'kyoto',label:'KYOTO',title:'Arashiyama & the Golden Pavilion',text:'Bamboo Grove and Tenryu-ji early; taxi across to Kinkaku-ji after lunch.',tag:'Full day'},
 {d:'27',w:'SUN',city:'kyoto',label:'KYOTO',title:'Fushimi Inari & Uji',text:'Torii gates before 08:00, then Byodo-in, tea streets and the Uji riverside.',tag:'Full day'},
 {d:'28',w:'MON',city:'tokyo',label:'TOKYO',title:'Kyoto → Tokyo & event prep',text:'Light Kyoto morning, midday Nozomi, hotel check-in, wristbands, supplies and hall-map planning.',tag:'Transfer'},
 {d:'29',w:'TUE',city:'comiket',label:'C109 · D1',title:'Comiket Day 1',text:'Priority circles first. Corporate booths also open. Regroup only at the agreed meeting point.',tag:'Big Sight'},
 {d:'30',w:'WED',city:'comiket',label:'C109 · D2',title:'Comiket Day 2',text:'Second genre rotation and final day for corporate booths. Unload purchases at the hotel.',tag:'Big Sight'},
 {d:'31',w:'THU',city:'comiket',label:'C109 · D3',title:'Comiket Day 3 & New Year’s Eve',text:'Final circles until 16:00. Rest, reserved dinner, then a small local shrine if energy allows.',tag:'Big Sight'},
 {d:'01',w:'FRI',city:'tokyo',label:'TOKYO',title:'Slow New Year’s Day',text:'Recovery morning, neighbourhood walk and hatsumode. Expect closures and major shrine queues.',tag:'New Year'},
 {d:'02',w:'SAT',city:'tokyo',label:'TOKYO',title:'Marunouchi, Ginza & first sales',text:'Imperial Palace area, then New Year shopping. Confirm the 2027 Palace event before travel.',tag:'Shopping'},
 {d:'03',w:'SUN',city:'tokyo',label:'TOKYO',title:'Anime shopping finale',text:'Akihabara, then choose Ikebukuro or Nakano Broadway. Pack purchases before sleeping.',tag:'Flexible'},
 {d:'04',w:'MON',city:'tokyo',label:'DEPART',title:'Final morning & NRT',text:'Light shopping or Asakusa. Collect bags by 13:00; leave central Tokyo by 14:15 for NRT 18:35.',tag:'Flight'}
];
const timeline=document.querySelector('#timeline');
timeline.innerHTML=days.map(x=>`<article class="day" data-city="${x.city}"><div class="date"><strong>${x.d}</strong><span>${x.w}</span></div><div class="city">${x.label}</div><div class="plan"><b>${x.title}</b><p>${x.text}</p></div><span class="tag">${x.tag}</span></article>`).join('');
document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;document.querySelectorAll('.day').forEach(d=>d.classList.toggle('hidden',f!=='all'&&d.dataset.city!==f));}));

const notes=document.querySelector('#circleNotes'),notesState=document.querySelector('#notesState');notes.value=localStorage.getItem('jp26-circle-notes')||'';let noteTimer;notes.addEventListener('input',()=>{notesState.textContent='Saving…';clearTimeout(noteTimer);noteTimer=setTimeout(()=>{localStorage.setItem('jp26-circle-notes',notes.value);notesState.textContent='Saved automatically';},350)});

const budget=[['Kyoto hotel · 3 nights','Triple room / apartment',90000],['Tokyo hotel · 7 nights','Ariake, Shimbashi or Toyosu',245000],['Intercity trains','Shinagawa–Kyoto–Tokyo · 3 people',84000],['Local transport','IC card travel and airport transfer',30000],['Food','11 days · group estimate',165000],['Admission & contingency','C109 tickets, attractions and buffer',36000]];
const budgetRows=document.querySelector('#budgetRows');budgetRows.innerHTML=budget.map((x,i)=>`<div class="budget-row"><label for="b${i}">${x[0]}<small>${x[1]}</small></label><div class="yen-input"><span>¥</span><input id="b${i}" inputmode="numeric" value="${localStorage.getItem('jp26-b'+i)||x[2]}" aria-label="${x[0]} budget"></div></div>`).join('');
function updateBudget(){let total=0;document.querySelectorAll('.yen-input input').forEach((el,i)=>{const n=Number(el.value.replace(/[^0-9]/g,''))||0;total+=n;localStorage.setItem('jp26-b'+i,n)});document.querySelector('#budgetTotal').textContent='¥'+total.toLocaleString();document.querySelector('#perPerson').textContent='¥'+Math.ceil(total/3).toLocaleString()+' per person';document.querySelector('#budgetFill').style.width=Math.min(100,total/650000*100)+'%'}document.querySelectorAll('.yen-input input').forEach(x=>x.addEventListener('input',updateBudget));updateBudget();

const checks=[['Book Kyoto accommodation','25–28 Dec · 3 nights'],['Book Tokyo accommodation','28 Dec–4 Jan · 7 nights'],['Reserve outbound Nozomi','Shinagawa → Kyoto · 25 Dec'],['Reserve return Nozomi','Kyoto → Tokyo · 28 Dec'],['Buy C109 admission','Separate admission for each required day'],['Build circle lists','Check daily genre and hall allocation'],['Arrange mobile data','eSIM, SIM or pocket Wi-Fi'],['Plan baggage space','Extra suitcase or delivery service'],['Reserve New Year meals','Especially dinner on 31 Dec / 1 Jan']];
const checkGrid=document.querySelector('#checkGrid');checkGrid.innerHTML=checks.map((x,i)=>`<label class="check-item"><input type="checkbox" data-check="${i}" ${localStorage.getItem('jp26-check-'+i)==='1'?'checked':''}><span><b>${x[0]}</b><small>${x[1]}</small></span></label>`).join('');document.querySelectorAll('[data-check]').forEach(c=>c.addEventListener('change',()=>localStorage.setItem('jp26-check-'+c.dataset.check,c.checked?'1':'0')));document.querySelector('#resetChecks').addEventListener('click',()=>{document.querySelectorAll('[data-check]').forEach(c=>{c.checked=false;localStorage.removeItem('jp26-check-'+c.dataset.check)})});
